### ISSUE TITLE
Instagram Galleries

### ISSUE THREAD

**Issue by cnassaney** [jordanmerrick/workflowdirectory#10]
# Instagram Galleries

This workflow creates a text file on icloud of user created Instagram IDs. It allows the user to pick an ID and display grids of the ID’s instagram feed. Swipe down on each gridded gallery to load the next. It has a repeat set for 20 times (grids), but you can make it shorter or longer.

Link: This workflow creates a text file on icloud of user created Instagram IDs. It allows the user to pick an ID and display grids of the ID’s instagram feed. Swipe down on each gridded gallery to load the next. It has a repeat set for 20 times (grids), but you can make it shorter or longer.

**Comment by cnassaney** [comment]
Not sure if link attached.. https://workflow.is/workflows/73469a87dcd5455584c672b4c3ae2734

**Comment by jordanmerrick** [comment]
Added to the repository.
