### ISSUE TITLE
How to install this workflows to my iPhone?

### ISSUE THREAD

**Issue by n0an** [jordanmerrick/workflowdirectory#11]
How can I install any of workflows to iphone? Using iTunes? I haven't found Workflow app in the "File Sharing" section of iTunes.
Or is there another way?

**Comment by jordanmerrick** [comment]
You can view any of the workflows (.wflow files) here on GitHub on your iPhone and then tap **Download**. Workflows cannot be synced via iTunes, you must download them on your iOS device directly.
