### ISSUE TITLE
Clipboard%2021%20okt.%202017%2022.47'FishingGO'%20in%20de%20App%20StoreClipboard%2021%20okt.%202017%2022.47

### ISSUE THREAD

**Issue by jphermans** [jordanmerrick/workflowdirectory#13]
(You can delete this text before creating your issue)

If you're experiencing a problem with a workflow, you can report the issue here and someone may be able to help. Provide a suitable title and description of the problem, along with which workflow is affected. Please assign the **problem** label to issues. In most cases, you should contact the workflow submitter first (available in the workflow's README).

You can also create an issue to submit a workflow. Please include a title, description, and **workflow.is** link.

**Comment by jordanmerrick** [comment]
Can you resubmit with a title, description, and link?
