### ISSUE TITLE
Add to food log in Evernote

### ISSUE THREAD

**Issue by skotzko** [jordanmerrick/workflowdirectory#16]
## Description
Quickly add to a Food Log notebook in Evernote. Note can include photo and/or text. 

In default setup, the new note will be tagged with: "meals", year (e.g. "2017"), and what it was (e.g. "snack"). 

Adapted from ["Take a Note" workflow.](http://www.thoughtasylum.com/blog/2015/2/24/workflow-ios-take-a-note.html)

## Link
https://workflow.is/workflows/d6148ef3c6c44534b1c65428d79de1a0

**Comment by jordanmerrick** [comment]
Added to repository.
