### ISSUE TITLE
Call with Skype

### ISSUE THREAD

**Issue by bodgelife** [jordanmerrick/workflowdirectory#17]
# Call with Skype

This workflow calls a phone number with Skype. It was created as a faster alternative to the Skype app’s UI. It can accept phone numbers from a share sheet, the clipboard, or user input, depending on context.

The workflow has been tested with Skype version 6.35.1.

Link: https://workflow.is/workflows/84f0399e421b48b08a9b47fe0a6de12f

**Comment by jordanmerrick** [comment]
Added to repository. Thanks!
