### ISSUE TITLE
Ultimate Insult Generator

### ISSUE THREAD

**Issue by ryantaylor16** [jordanmerrick/workflowdirectory#21]
The Ultimate Insult Generator
http://cdn1-www.craveonline.com/assets/uploads/2013/07/man_file_1045204_ultimate-insult-creator-final.png 
[Ultimate Insult Generator.zip](https://github.com/jordanmerrick/workflowdirectory/files/1503640/Ultimate.Insult.Generator.zip)

**Comment by jordanmerrick** [comment]
Thanks for the submission! A random insult generator did make me chuckle. I can't add this to the directory due to the profanity and language it contains though.
