### ISSUE TITLE
EXIF Details Of Image v2

### ISSUE THREAD

**Issue by g33kyM0m** [jordanmerrick/workflowdirectory#29]
WF Link: [https://workflow.is/workflows/65d0264bdd2a47aa90272dc96e3907ee](https://workflow.is/workflows/65d0264bdd2a47aa90272dc96e3907ee)

## Changes to This Version

1. Added image name (editable), date details saved, & size Info (in px and inches) as a page header.
2. Also separated metadata dictionary into a separate table for ease of viewing.
3. Added option to save as PDF

**Comment by melangue** [comment]
Awesome update to my workflow, will be definitely using it!

**Comment by g33kyM0m** [comment]
:) glad to help

**Comment by mbierman** [comment]
Nice work!
