### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by b0park** [jordanmerrick/workflowdirectory#32]
It appears the OCR and Translate workflow no longer works. I used a brand new API to no success. I noticed that the URL for the cognitive services were different, tried updating that but I still fail at the last step of quick view which makes me believe its never reaching the cognitive service in the first place. Has anyone used it recently with success?

**Comment by jordanmerrick** [comment]
Thanks for reporting. I'll remove the OCR workflows for now. The API has changed quite significantly, so a new workflow would need to be created.
