### ISSUE TITLE
Install From Workflow Directory

### ISSUE THREAD

**Issue by MathWhiz** [jordanmerrick/workflowdirectory#6]
# Install From Workflow Directory

Allows user to select and download Workflows located in the Workflow Directory.

Link: https://workflow.is/workflows/45a2bbdbee5c40d5a890079ae4bae584

**Comment by jordanmerrick** [comment]
Great workflow! Just added https://github.com/jordanmerrick/workflowdirectory/tree/master/workflows/Install%20From%20Workflow%20Directory

**Comment by MathWhiz** [comment]
Awesome!
