### ISSUE TITLE
Celsius to Fahrenheit

### ISSUE THREAD

**Issue by Jim-Cluff-David** [jordanmerrick/workflowdirectory#8]
This is my first Workflow. It converts degrees in Celsius to Fahrenheit. I’d like to query the user as to which conversion they would like C to F or F to C. I can’t figure out how to use the selection features or the branching commands to do multiple conversions.

**Comment by Jim-Cluff-David** [comment]
https://workflow.is/workflows/324d315f404a411dbf0eeffa526027f6

**Comment by jordanmerrick** [comment]
Added to repository.
